baseURL: ""
languageCode: "en-us"
title: "WireMock"
copyright: "© 2023 WireMock"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true


paginate: 24

taxonomies:
  tag: tags
permalinks:
  tags: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  navbar:
    - name: Main site
      url: "https://wiremock.org/"
      pre: '<img src="https://wiremock.org/images/logos/doc-sections/home.svg" class="nav-icon" />'
    - name: Docs
      url: "https://wiremock.org/docs"
      pre: '<img src="https://wiremock.org/images/logos/doc-sections/document.svg" class="nav-icon" />'
    - name: Need help?
      url: "https://wiremock.org/support"
      pre: '<img src="https://wiremock.org/images/logos/doc-sections/help-mono.svg" class="nav-icon" />'
    - name: Participate
      url: "https://wiremock.org/participate"
      pre: '<img src="https://wiremock.org/images/logos/doc-sections/community.svg" class="nav-icon" />'
    - name: Resources
      url: "https://wiremock.org/external-resources"
      pre: '<img src="https://wiremock.org/images/logos/doc-sections/plus.svg" class="nav-icon" />'