# description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
logo: "/images/wireMockLogo.png"
logo_mark: "/images/shortLogo.png"
logo_cloud: "/images/Cloud_Logo.png"
author: "WireMock"
github: "#"
ogimage: "/images/wireMockLogo.png"
sitename: "WireMock"
twitter: "https://twitter.com/wiremockorg"
description: "Mock API library: samples, templates, and quick starts"
mainSections:
  - catalog
cta:
  heading: Ready to accelerate your development flow
  subheading: Shorter release cycles, more predictable schedules and fewer defects in production.
  image: /images/cta.svg
  button:
    text: Start Mocking for Free
    url: "https://wiremock.io/product?utm_source=library.wiremock.org&utm_medium=referral&utm_content=root&utm_campaign=homepage_2022_baseline"
  note: "*Free forever. No credit card needed"