baseURL: ""
languageCode: "en-us"
title: "WireMock"
copyright: "© 2023 WireMock"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 24

taxonomies:
  tag: tags
permalinks:
  tags: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true           
menu:
   navbar:
   - name: Docs
     url: "https://wiremock.org/docs"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/document.svg" class="nav-icon" />'
   - name: Need help?
     url: "https://wiremock.org/support"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/help-mono.svg" class="nav-icon" />'
   - name: Participate
     url: "https://wiremock.org/participate"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/community.svg" class="nav-icon" />'
   - name: Resources
     url: "https://wiremock.org/external-resources"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/plus.svg" class="nav-icon" />'
  # - name: Product two
  #   url: "#"
  #   parent: Link
  #   weight: 120
  # - name: Product three
  #   url: "#"
  #   parent: Link
  #   weight: 130
  # - name: Product four
  #   url: "#"
  #   parent: Link
  #   weight: 140
  # - name: Link2
  #   url: "#"
  #   weight: 20
  # - name: Link3
  #   url: "#"
  #   weight: 30

  #social:
  # - name: Facebook
  #   url: "#"
  #   pre: facebook
  #   weight: 10
  # - name: Instagram
  #   url: "#"
  #   pre: instagram
  #   weight: 20
  # - name: Twitter
  #   url: "#"
  #   pre: twitter
  #   weight: 30
#  - name: GitHub
#    url: "https://github.com/wiremock"
#    pre: github
#    weight: 10
        
params:
  # description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  logo: "/images/wireMockLogo.png"
  logo_mark: "/images/shortLogo.png"
  logo_cloud: "/images/Cloud_Logo.png"
  author: "WireMock"
  github: "#"
  ogimage: "/images/wireMockLogo.png"
  sitename: "WireMock"
  twitter: "https://github.com/wiremock"
  description: "Mock API library: samples, templates, and quick starts"
  mainSections:
  - api

  cta:
    heading: Have More Questions?
    subheading: 
    image: images/cta.svg
    button:
      text: Contact Us
      url: "https://share-eu1.hsforms.com/1YSKnSP93Tsig1JoO3lXSawfbdiq"
  