baseURL: ""
languageCode: "en-us"
title: "WireMock"
copyright: "© 2023 WireMock"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

googleAnalytics: UA-36386229-2

paginate: 24

taxonomies:
  tag: tags
permalinks:
  tags: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true           
menu:
   navbar:
   - name: Main site
     url: "https://wiremock.org/"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/home.svg" class="nav-icon" />'
   - name: Docs
     url: "https://wiremock.org/docs"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/document.svg" class="nav-icon" />'
   - name: Need help?
     url: "https://wiremock.org/support"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/help-mono.svg" class="nav-icon" />'
   - name: Participate
     url: "https://wiremock.org/participate"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/community.svg" class="nav-icon" />'
   - name: Resources
     url: "https://wiremock.org/external-resources"
     pre: '<img src="https://wiremock.org/images/logos/doc-sections/plus.svg" class="nav-icon" />'

  #social:
  # - name: Facebook
  #   url: "#"
  #   pre: facebook
  #   weight: 10
  # - name: Instagram
  #   url: "#"
  #   pre: instagram
  #   weight: 20
  # - name: Twitter
  #   url: "#"
  #   pre: twitter
  #   weight: 30
#  - name: GitHub
#    url: "https://github.com/wiremock"
#    pre: github
#    weight: 10
        
params:
  # description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  logo: "/images/wireMockLogo.png"
  logo_mark: "/images/shortLogo.png"
  logo_cloud: "/images/Cloud_Logo.png"
  author: "WireMock"
  github: "#"
  ogimage: "/images/wireMockLogo.png"
  sitename: "WireMock"
  twitter: "https://twitter.com/wiremockorg"
  description: "Mock API library: samples, templates, and quick starts"
  mainSections:
  - catalog
  cta:
    heading: Ready to accelerate your development flow
    subheading: Shorter release cycles, more predictable schedules and fewer defects in production.
    image: /images/cta.svg
    button:
      text: Start Mocking for Free
      url: "https://wiremock.io/product?utm_source=library.wiremock.org&utm_medium=referral&utm_content=root&utm_campaign=homepage_2022_baseline"
    note: "*Free forever. No credit card needed"
  