baseURL: ""
languageCode: "en-us"
title: "WireMock"
description: 
copyright: "© 2023 WireMock"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 24

taxonomies:
  tag: tags
permalinks:
  tags: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true           
menu:
  navbar:
  - name: Link
    url: "#"
    weight: 10
  - name: Product one
    url: "#"
    parent: Link
    weight: 110
  - name: Product two
    url: "#"
    parent: Link
    weight: 120
  - name: Product three
    url: "#"
    parent: Link
    weight: 130
  - name: Product four
    url: "#"
    parent: Link
    weight: 140
  - name: Link2
    url: "#"
    weight: 20
  - name: Link3
    url: "#"
    weight: 30

  navbar_cta:
  - name: WireMock Cloud
    url: "https://wiremock.io/?utm_source=wiremock.org&utm_medium=masthead&utm_campaign=homepage_2022_baseline"
    pre: primary
    weight: 10

  social:
  # - name: Facebook
  #   url: "#"
  #   pre: facebook
  #   weight: 10
  # - name: Instagram
  #   url: "#"
  #   pre: instagram
  #   weight: 20
  # - name: Twitter
  #   url: "#"
  #   pre: twitter
  #   weight: 30
  - name: GitHub
    url: "https://github.com/wiremock"
    pre: github
    weight: 10

  footer:
  - name: Services
    weight: 10
  - name: Company
    weight: 20
  - name: Resources
    weight: 30
        
params:
  # description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  logo: "/images/wireMockLogo.png"
  logo_mark: "/images/shortLogo.png"
  author: "WireMock"
  github: "#"
  ogimage: "/images/wireMockLogo.png"
  sitename: "WireMock"
  # twitter: "#"
  mainSections:
  - api

  cta:
    heading: Have More Questions?
    subheading: 
    image: images/cta.svg
    button:
      text: Contact Us
      url: "#"
  